name: Test Hexo Site with Playwright

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test-hexo-site:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Playwright test repository (the current repository)
      - name: Checkout Playwright repository
        uses: actions/checkout@v3

      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v3
        with:
          repository: PD438/Hexo  # Your Hexo repo
          path: hexo-site-repo

      # Set up Node.js for the Hexo site
      - name: Set up Node.js for Hexo
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version
          cache: 'npm'

      # Install Hexo dependencies
      - name: Install Hexo dependencies
        working-directory: hexo-site-repo
        run: npm ci

      # Generate the static Hexo website
      - name: Generate Hexo site
        working-directory: hexo-site-repo
        run: npx hexo generate

      # Start the Hexo server in the background
      - name: Start Hexo server
        working-directory: hexo-site-repo
        run: |
          npx hexo server &  # Start Hexo server in the background
          echo $! > hexo.pid  # Store server process ID for later termination

      # Wait for the Hexo server to be ready
      - name: Wait for Hexo server to start
        run: npx wait-on http://localhost:4000

      # Install Playwright dependencies
      - name: Install Playwright dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run Playwright tests against the running Hexo site
      - name: Run Playwright tests
        run: npx playwright test

      # Stop the Hexo server
      - name: Stop Hexo server
        if: always()
        working-directory: hexo-site-repo
        run: |
          kill $(cat hexo.pid)  # Stop the Hexo server using the stored process ID
